#!/bin/bash
dst=/d/rcownie/viewer
rm -rf $dst
mkdir $dst
cp viewer_readme.txt ${dst}/README.txt
cd /d/xlibs/opencv/build/x64/vc15/bin
cp -p *.dll $dst
cd /d/rcownie/librealuvc-build/Release
cp -p *.dll viewer.exe $dst
