if(BUILD_ANDROID AND (NOT OpenCV_DIR OR OpenCV_DIR MATCHES "NOTFOUND"))
  if(BUILD_ANDROID64)
    set(_abi_name "arm64-v8a")
  else()
    set(_abi_name "armeabi-v7a")
  endif()
  set(OpenCV_DIR "${EXTERNAL_LIBRARY_DIR}/opencv-3.2/sdk/native/jni/abi-${_abi_name}" CACHE PATH "path to JNI OpenCVConfig.cmake" FORCE)
  set(OpenCV_PREFERRED 3.2)
else()
  set(OpenCV_PREFERRED 4.0)
endif()
set(OpenCV_STATIC ON)
find_package(OpenCV ${OpenCV_PREFERRED} REQUIRED)
